// Generated by CoffeeScript 1.10.0
var Assessments,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Assessments = (function(superClass) {
  extend(Assessments, superClass);

  function Assessments() {
    return Assessments.__super__.constructor.apply(this, arguments);
  }

  Assessments.prototype.model = Assessment;

  Assessments.prototype.url = 'assessment';

  Assessments.prototype.pouch = {
    viewOptions: {
      key: 'assessment'
    }
  };

  Assessments.prototype.comparator = function(model) {
    return model.get("name");
  };

  return Assessments;

})(Backbone.Collection);
