// Generated by CoffeeScript 1.10.0
var Assessment;

Assessment = Backbone.Model.extend({
  url: 'assessment',
  VERIFY_TIMEOUT: 20 * 1000,
  initialize: function(options) {
    if (options == null) {
      options = {};
    }
    return this.subtests = new Subtests;
  },
  verifyConnection: (function(_this) {
    return function(callbacks) {
      if (callbacks == null) {
        callbacks = {};
      }
      if (callbacks.error != null) {
        _this.timer = setTimeout(callbacks.error, _this.VERIFY_TIMEOUT);
      }
      return $.ajax({
        url: Tangerine.settings.urlView("group", "byDKey"),
        dataType: "jsonp",
        data: {
          keys: ["testtest"]
        },
        timeout: _this.VERIFY_TIMEOUT,
        success: function() {
          clearTimeout(_this.timer);
          return typeof callbacks.success === "function" ? callbacks.success() : void 0;
        }
      });
    };
  })(this),
  deepFetch: function(opts) {
    if (opts == null) {
      opts = {};
    }
    opts.error = opts.error || $.noop;
    opts.success = opts.success || $.noop;
    return this.fetch({
      error: opts.error,
      success: (function(_this) {
        return function() {
          console.log(_this.subtests);
          _this.subtests = new Subtests;
          _this.subtests.assessment = _this;
          return _this.subtests.fetch({
            viewOptions: {
              key: "subtest-" + _this.id
            },
            error: function() {
              return console.log("that failed");
            },
            success: function(subtests) {
              subtests.ensureOrder();
              return opts.success.apply(subtests.assessment, arguments);
            }
          });
        };
      })(this)
    });
  }
});
