// Generated by CoffeeScript 1.10.0
var KlassResults,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

KlassResults = (function(superClass) {
  extend(KlassResults, superClass);

  function KlassResults() {
    return KlassResults.__super__.constructor.apply(this, arguments);
  }

  KlassResults.prototype.url = "result";

  KlassResults.prototype.model = KlassResult;

  KlassResults.prototype.pouch = {
    viewOptions: {
      key: 'result'
    }
  };

  KlassResults.prototype.initialize = function(options) {
    if (options == null) {
      options = {};
    }
    if (!((options.showOld != null) && options.showOld === true)) {
      return this.on("all", (function(_this) {
        return function(event) {
          var i, j, len, len1, ref, result, resultId, results, toRemove;
          toRemove = [];
          ref = _this.models;
          for (i = 0, len = ref.length; i < len; i++) {
            result = ref[i];
            if (result.has("old")) {
              toRemove.push(result.id);
            }
          }
          results = [];
          for (j = 0, len1 = toRemove.length; j < len1; j++) {
            resultId = toRemove[j];
            results.push(_this.remove(resultId, {
              silent: true
            }));
          }
          return results;
        };
      })(this));
    }
  };

  return KlassResults;

})(Backbone.Collection);
