// Generated by CoffeeScript 1.10.0
var Curricula,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Curricula = (function(superClass) {
  extend(Curricula, superClass);

  function Curricula() {
    return Curricula.__super__.constructor.apply(this, arguments);
  }

  Curricula.prototype.url = "curriculum";

  Curricula.prototype.model = Curriculum;

  Curricula.prototype.pouch = {
    viewOptions: {
      key: 'curriculum'
    }
  };

  return Curricula;

})(Backbone.Collection);
