// Generated by CoffeeScript 1.10.0
var CurriculaListView,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CurriculaListView = (function(superClass) {
  extend(CurriculaListView, superClass);

  function CurriculaListView() {
    this.render = bind(this.render, this);
    return CurriculaListView.__super__.constructor.apply(this, arguments);
  }

  CurriculaListView.prototype.className = "CurriculaListView";

  CurriculaListView.prototype.tagName = "ul";

  CurriculaListView.prototype.initialize = function(options) {
    var base;
    this.views = [];
    this.curricula = options.curricula;
    return typeof (base = this.curricula).on === "function" ? base.on("all", this.render) : void 0;
  };

  CurriculaListView.prototype.render = function() {
    if (this.curricula.length === 0) {
      return;
    }
    this.$el.html("<h1>Curricula</h1>");
    this.closeViews;
    this.curricula.each((function(_this) {
      return function(curriculum) {
        var view;
        view = new CurriculumListElementView({
          "curriculum": curriculum
        });
        view.render();
        _this.$el.append(view.el);
        return _this.views.push(view);
      };
    })(this));
    return this.trigger("rendered");
  };

  CurriculaListView.prototype.onClose = function() {
    return this.closeViews();
  };

  CurriculaListView.prototype.closeViews = function() {
    var i, len, ref, results, view;
    ref = this.views;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      view = ref[i];
      results.push(typeof view.close === "function" ? view.close() : void 0);
    }
    return results;
  };

  return CurriculaListView;

})(Backbone.View);
