// Generated by CoffeeScript 1.10.0
var Curriculum,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Curriculum = (function(superClass) {
  extend(Curriculum, superClass);

  function Curriculum() {
    return Curriculum.__super__.constructor.apply(this, arguments);
  }

  Curriculum.prototype.url = "curriculum";

  return Curriculum;

})(Backbone.Model);
