// Generated by CoffeeScript 1.10.0
var Students,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Students = (function(superClass) {
  extend(Students, superClass);

  function Students() {
    return Students.__super__.constructor.apply(this, arguments);
  }

  Students.prototype.model = Student;

  Students.prototype.url = "student";

  Students.prototype.pouch = {
    viewOptions: {
      key: 'student'
    }
  };

  Students.prototype.comparator = function(model) {
    return model.get("name").toLowerCase();
  };

  return Students;

})(Backbone.Collection);
