// Generated by CoffeeScript 1.10.0
var CsvMenuView,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CsvMenuView = (function(superClass) {
  extend(CsvMenuView, superClass);

  function CsvMenuView() {
    return CsvMenuView.__super__.constructor.apply(this, arguments);
  }

  CsvMenuView.prototype.className = "CsvMenuView";

  CsvMenuView.prototype.initialize = function(options) {
    var groupName, klassId;
    klassId = options.parent.options.klass.id;
    groupName = Tangerine.settings.get("groupName");
    return document.location = "http://databases.tangerinecentral.org/_csv/class/" + groupName + "/" + klassId;
  };

  return CsvMenuView;

})(Backbone.View);
