// Generated by CoffeeScript 1.10.0
Tangerine.ReportWarnings = {
  KlassToDateView: function(rawData) {
    var bucketKey, html, percentages, ref, result;
    result = [];
    ref = rawData.percentages;
    for (bucketKey in ref) {
      percentages = ref[bucketKey];
      html = "";
      if (this.nUnderX(0.2, 0.75, percentages)) {
        html += "<p>More than 20% of students got less than 75% on the " + bucketKey + " assessment. Re-teach the " + bucketKey + " component of the lesson during the next lesson.</p>";
      }
      result.push({
        "html": html
      });
    }
    return result;
  },
  StudentToDateView: function(rawData) {
    var bucketKey, html, percentage, ref, result;
    result = [];
    ref = rawData.percentages;
    for (bucketKey in ref) {
      percentage = ref[bucketKey];
      html = "";
      if ((_.flatten(percentage) / 100) < .75) {
        html += "<p>" + rawData.studentName + " got less than 75% on the " + bucketKey + " assessment. Re-teach the " + bucketKey + " component from applicable lessons during the next lesson.</p>";
      }
      result.push({
        "html": html
      });
    }
    return result;
  },
  nUnderX: function(n, x, percentages) {
    var i, len, percentage, totalCount, underCount;
    underCount = 0;
    totalCount = 0;
    for (i = 0, len = percentages.length; i < len; i++) {
      percentage = percentages[i];
      totalCount++;
      if (percentage / 100 < x) {
        underCount++;
      }
    }
    return (underCount / totalCount) > n;
  }
};
